app:
  logFile: log/gin.log
  httpPort: 8080
  webSocketPort: 8089
  rpcPort: 9001
  httpUrl: 127.0.0.1:8080
  webSocketUrl:  127.0.0.1:8089


redis:
  addr: "redis:6379"
  password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
  DB: 0
  poolSize: 30
  minIdleConns: 30